language: ruby
rvm:
  - 2.0.0

before_script: "bundle exec rake db:drop db:create db:migrate" 
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_script:
  - cp config/database.yml.travis config/database.yml
script: "bundle exec rake"